/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'avb' at '1/27/17 10:29 PM' with Gradle 2.13
 *
 * @author avb, @date 1/27/17 10:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
